
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '90FDDB1BDEB5ED698E2DADFA7519DE4D'
    
_lr_action_items = {'NUMBER':([0,2,4,9,10,12,13,],[1,1,1,1,1,1,1,]),'LBRACKET':([0,2,4,9,10,12,13,],[4,4,4,4,4,4,4,]),'TIMES':([1,5,6,7,14,15,16,17,18,19,],[-7,-6,-8,12,-9,12,12,-10,-4,-5,]),'LPAREN':([0,2,4,9,10,12,13,],[2,2,2,2,2,2,2,]),'RPAREN':([1,5,6,7,8,14,15,16,17,18,19,],[-7,-6,-8,-3,14,-9,-2,-1,-10,-4,-5,]),'DIVIDE':([1,5,6,7,14,15,16,17,18,19,],[-7,-6,-8,13,-9,13,13,-10,-4,-5,]),'VARIABLE':([0,2,4,9,10,12,13,],[6,6,6,6,6,6,6,]),'MINUS':([1,3,5,6,7,8,11,14,15,16,17,18,19,],[-7,9,-6,-8,-3,9,9,-9,-2,-1,-10,-4,-5,]),'PLUS':([1,3,5,6,7,8,11,14,15,16,17,18,19,],[-7,10,-6,-8,-3,10,10,-9,-2,-1,-10,-4,-5,]),'RBRACKET':([1,5,6,7,11,14,15,16,17,18,19,],[-7,-6,-8,-3,17,-9,-2,-1,-10,-4,-5,]),'$end':([1,3,5,6,7,14,15,16,17,18,19,],[-7,0,-6,-8,-3,-9,-2,-1,-10,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'factor':([0,2,4,9,10,12,13,],[5,5,5,5,5,18,19,]),'term':([0,2,4,9,10,],[7,7,7,15,16,]),'expression':([0,2,4,],[3,8,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','yacc.py',9),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','yacc.py',13),
  ('expression -> term','expression',1,'p_expression_term','yacc.py',17),
  ('term -> term TIMES factor','term',3,'p_term_times','yacc.py',21),
  ('term -> term DIVIDE factor','term',3,'p_term_div','yacc.py',25),
  ('term -> factor','term',1,'p_term_factor','yacc.py',29),
  ('factor -> NUMBER','factor',1,'p_factor_num','yacc.py',33),
  ('factor -> VARIABLE','factor',1,'p_factor_variable','yacc.py',37),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_param','yacc.py',41),
  ('factor -> LBRACKET expression RBRACKET','factor',3,'p_factor_blacket','yacc.py',45),
]
