
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '6B67D926BA28940595B0C9968DD204C7'
    
_lr_action_items = {'LPAREN':([0,1,8,9,10,11,12,],[1,1,1,1,1,1,1,]),'NUMBER':([0,1,8,9,10,11,12,],[5,5,5,5,5,5,5,]),'VARIABLE':([0,1,8,9,10,11,12,],[2,2,2,2,2,2,2,]),'PLUS':([2,3,4,5,6,7,13,14,15,16,17,18,19,],[-8,10,-6,-7,-3,10,-9,10,-2,-1,-5,-4,-10,]),'RBRACKET':([2,4,5,6,13,14,15,16,17,18,19,],[-8,-6,-7,-3,-9,19,-2,-1,-5,-4,-10,]),'DIVIDE':([2,4,5,6,13,15,16,17,18,19,],[-8,-6,-7,12,-9,12,12,-5,-4,-10,]),'LBRACKET':([2,],[8,]),'MINUS':([2,3,4,5,6,7,13,14,15,16,17,18,19,],[-8,9,-6,-7,-3,9,-9,9,-2,-1,-5,-4,-10,]),'RPAREN':([2,4,5,6,7,13,15,16,17,18,19,],[-8,-6,-7,-3,13,-9,-2,-1,-5,-4,-10,]),'TIMES':([2,4,5,6,13,15,16,17,18,19,],[-8,-6,-7,11,-9,11,11,-5,-4,-10,]),'$end':([2,3,4,5,6,13,15,16,17,18,19,],[-8,0,-6,-7,-3,-9,-2,-1,-5,-4,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'factor':([0,1,8,9,10,11,12,],[4,4,4,4,4,17,18,]),'term':([0,1,8,9,10,],[6,6,6,15,16,]),'expression':([0,1,8,],[3,7,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','yacc.py',9),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','yacc.py',13),
  ('expression -> term','expression',1,'p_expression_term','yacc.py',17),
  ('term -> term DIVIDE factor','term',3,'p_term_div','yacc.py',21),
  ('term -> term TIMES factor','term',3,'p_term_times','yacc.py',25),
  ('term -> factor','term',1,'p_term_factor','yacc.py',30),
  ('factor -> NUMBER','factor',1,'p_factor_num','yacc.py',34),
  ('factor -> VARIABLE','factor',1,'p_factor_variable','yacc.py',38),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_param','yacc.py',42),
  ('factor -> VARIABLE LBRACKET expression RBRACKET','factor',4,'p_factor_array','yacc.py',46),
]
